# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Catarina Fagundes Burghi
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  Hello! If you are reading this you are either one of my friends, someone on the robotics team or a random person. 
  Anyways, welcome. This website has a main purpose for me (to learn).
  I could use this website for many things, like a jornal on how to program (an idea a friend gave me)
  Or to make games, or just to make a journal,= (which I'll probably do.)
  Anyways if you are still here, go and have fun! Enjoy my website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: catarina_burghi
    github:  catarinaburghi
    instagram: catarina_burghi
    snapchat: bass.cat2019


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
